AllCops:
  TargetRubyVersion: 2.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - honeycomb-beeline.gemspec

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
