AllCops:
  TargetRubyVersion: 2.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - honeycomb-beeline.gemspec

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Naming/FileName:
  Exclude:
    - lib/honeycomb-beeline.rb

Style/SymbolProc:
  Exclude:
    - lib/honeycomb/span.rb
