language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
script: bundle exec rake test
